/*
 * pwix:forums/src/common/js/constants.js
 */

// access to a forum
FRS_FORUM_PUBLIC = 'FRS_FORUM_PUBLIC';
FRS_FORUM_PRIVATE = 'FRS_FORUM_PRIVATE';

// participation to the public forums
FRS_USER_ANYBODY = 'FRS_USER_ANYBODY';
FRS_USER_LOGGEDIN = 'FRS_USER_LOGGEDIN';
FRS_USER_EMAILADDRESS = 'FRS_USER_EMAILADDRESS';
FRS_USER_EMAILVERIFIED = 'FRS_USER_EMAILVERIFIED';
FRS_USER_APPFN = 'FRS_USER_APPFN';

// forum moderation
FRS_MODERATE_NONE = 'FRS_MODERATE_NONE';
FRS_MODERATE_APRIORI = 'FRS_MODERATE_APRIORI';
FRS_MODERATE_APOSTERIORI = 'FRS_MODERATE_APOSTERIORI';

// verbosity level
FRS_VERBOSE_NONE           = 0x00;
FRS_VERBOSE_CONFIGURE      = 0x01 <<  0;
FRS_VERBOSE_STARTUP        = 0x01 <<  1;
FRS_VERBOSE_READY          = 0x01 <<  2;     // when ready(), client-only
FRS_VERBOSE_COLLECTIONS    = 0x01 <<  3;

// non exported constants

FRSI18N = 'pwix:forums:i18n';
